### ISSUE TITLE
Question: Relation to io/fs?

### ISSUE THREAD

**Issue by nmeum** [go-git/go-billy#11]
How does this library relate to the [`io/fs` draft](https://golang.org/s/draft-iofs-design) which has been accepted recently and will be [a part of go 1.16](https://tip.golang.org/pkg/io/fs/), which is scheduled to be released in February? How will this affect [go-git](https://github.com/go-git/go-git) and will go-git migrate to `io/fs`?

**Comment by happybeing** [comment]
Just reading the abstract, the `io/fs` draft says it is for read-only filetrees so it wouldn't be suitable replacement for `go-git`'s `go-billy` filesystem. So maybe that isn't what you are asking - of not can you clarify?

**Comment by nmeum** [comment]
My understanding is that support for writeable files is [supposed to be added later on](https://github.com/golang/go/issues/41190#issuecomment-690848889):

> It's true that if we later want to add writing, […]

It should also be possible to employ the [extension pattern](https://go.googlesource.com/proposal/+/master/design/draft-iofs.md#extension-interfaces-and-the-extension-pattern) to implement write-related functionality on top of `fs.Fileystem` [\[1\]](https://go.googlesource.com/proposal/+/master/design/draft-iofs.md#design):

> Although the initial interface is limited to read-only file systems, the design can be extended to support write operations later, even from third-party packages.

**Comment by happybeing** [comment]
Reading the issue comment (your "supposed..." link), it doesn't sound like there's an intention to support writing yet, but to put it off and maybe not do it at all. Yes, he acknowledges it could be added later, but it doesn't seem to be in the mind of the poster to do that. Read the last line.

So I think your question is moot for now, but I'm not replying in behalf of the maintainers. I was curious about the possibility because I've been using `go-billy` recently and think it would be useful to have that kind of flexibility in `io/fs`.

Do you have a reason to want this convergence?

**Comment by nmeum** [comment]
> So I think your question is moot for now, […]

As I said: One can use the extension pattern to implement missing functionality.

> Do you have a reason to want this convergence?

Yes, `io/fs` is much closer integrated with the standard library. For example, you can simply [pass an `fs.FS` to a `http.FileServer`](https://tip.golang.org/pkg/net/http/#FileServer) many [other functions from the standard library](https://go.googlesource.com/proposal/+/master/design/draft-iofs.md#adjustments-to-os) have also been adjusted accordingly. The draft further explains the advantages of this approach, please consult it for further information.

**Comment by luisdavim** [comment]
Something like https://github.com/forensicanalysis/gitfs to make them compatible would be nice to have out-of-the-box.

**Comment by evankanderson** [comment]
Would a PR to add `billy.AsFS(billy.Filesystem) fs.FS` (or some larger union type that included `fs.FS`, `fs.ReadDirFS`, `fs.StatFS`, etc) be accepted?  I have an implementation I wrote to enable some integration with another library which is using `io/fs`.

**Comment by pjbgf** [comment]
Hey @evankanderson, I would be happy to review the PR and discuss it further. Just as a thought, this could potentially be a new package in `helper` that augments a `billy.Filesystem` with the `io/fs` interface, like we already do with `helper/chroot`.

**Comment by evankanderson** [comment]
Awesome!  I discovered that the Go standard library has a test suite for `fs.FS` implementations already, so I mostly just re-used that (except that `fs.FS` is read-only at the moment, which may be a blocker for adoption by go-git).

I also couldn't find a CONTRIBUTING.md or the like in this repo, so I just took a best-guess.
