### ISSUE TITLE
question: chroot does not process path target ​​from symlink?

### ISSUE THREAD

**Issue by gebv** [go-git/go-billy#16]
Chroot does not process path target ​​from symlink? It is normal behavior?

Follow concept code
```golang
baseDir := "/foo/bar"
fs := chroot.New(&billyFilesystemSomeImpl{}, baseDir)
// lrwxr-xr-x /foo/bar/lint-to-tmp -> /tmp
fs.Open("/foo/bar/link-to-tmp")
// opened without errors
```

**Comment by pjbgf** [comment]
For prosperity: this is the documented behaviour for [ChrootOS](https://github.com/go-git/go-billy/blob/a0a6b08d90329eed7f4619f6958efba57e436537/osfs/os_chroot.go#L14-L23), which largely aligns with its intention of chrooting the FS. [BoundOS](https://github.com/go-git/go-billy/blob/a0a6b08d90329eed7f4619f6958efba57e436537/osfs/os_bound.go#L38-L48) behaves differently by being able to represent symlinks even outside of the dir it is bound to.
