### ISSUE TITLE
new release to include latest commit?

### ISSUE THREAD

**Issue by ericDeliot** [go-git/go-billy#22]
Hi,

Could you issue a new release to include the latest commits (walk code) that didn't make it in the last one? Thanks.

Eric

**Comment by shilkin** [comment]
Agree. I'm going to use `util.Walk` and currently I have to rely on commit hash.

**Comment by tnqv** [comment]
`util.Walk` seems good, I want to use it too.

**Comment by pjbgf** [comment]
Tag [v5.4.0](https://github.com/go-git/go-billy/releases/tag/v5.4.0) includes this feature.
