### ISSUE TITLE
osfs doesn't seem to be referencing the underlying chroot

### ISSUE THREAD

**Issue by jawr** [go-git/go-billy#9]
I haven't dug too deep/tested this yet, but it seems to me that in a lot of instances methods are referencing the stdlib os rather than fs for operations, i.e. https://github.com/go-git/go-billy/blob/master/osfs/os.go#L45 there is no reference to the chroot

Please feel free to ignore this if I'm being a wally.

**Comment by smola** [comment]
@jawr What are you trying to accomplish? The `chroot` subpackage in go-billy works on top of another go-billy filesystem, not the other way around. When you use `osfs.New(basedir)`, the `osfs` filesystem is wrapped with a `chroot` to make sure that all operations are relative to `basedir`.

**Comment by jawr** [comment]
I haven't begun coding yet, but my goal is to create a chrooted FS, which go-billy seems to do. However when I was looking through the code it appears like there are some issues.

Creating an osfs:

```
func New(baseDir string) billy.Filesystem {
	return chroot.New(&OS{}, baseDir)
}
```

Perfect, `fs` should now be working with the chroot system, and all methods should have the chroot helper ensuring it's bound to the chroot. But once we start looking at the methods, they reference the stdlib `os` instead of `fs`, i.e.:

```
func (fs *OS) createDir(fullpath string) error {
	dir := filepath.Dir(fullpath)
	if dir != "." {
		if err := os.MkdirAll(dir, defaultDirectoryMode); err != nil {
			return err
		}
	}

	return nil
}
```

Here we never reference `fs`/the chroot system and instead are working directly with the stldib `os`. I expected that it would be:

```
func (fs *OS) createDir(fullpath string) error {
	dir := filepath.Dir(fullpath)
	if dir != "." {
		if err := fs.MkdirAll(dir, defaultDirectoryMode); err != nil {
			return err
		}
	}

	return nil
}
```

To ensure that the fullpath is relative to basedir. Again, apologies if I'm missing the point here.

**Comment by jawr** [comment]
Closing issue, as I was being a wally!
